dist: trusty
language: node_js
services:
  - mongodb
node_js:
- '7'
addons:
  ssh_known_hosts: $DEPLOY_SSH_HOST
  apt:
    packages:
      - sshpass
before_script:
  - mv travis.secrets.js src/secrets.js
  - sleep 15
  - mongo sfstest --eval 'db.createUser({user: "testuser", pwd: "test", roles: ["readWrite"]});'
script: npm run test:ci
deploy:
  skip_cleanup: true
  provider: script
  script: sshpass -p $DEPLOY_SSH_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_SSH_USER@$DEPLOY_SSH_HOST -t "$DEPLOY_SSH_PATH/deploy.sh"
  on:
    tags: true
